name: Go Lang CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@b4ffde65f46336ab88eb53be808477a3936bae11 
      with:
        go-version: '1.22.1'

    - name: Check out code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11


    - name: Build
      run: go build -o myapp main.go

    - name: Run the app
      run: ./myapp

    - name: Set up QEMU
      uses: docker/setup-qemu-action@b4ffde65f46336ab88eb53be808477a3936bae11 

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@b4ffde65f46336ab88eb53be808477a3936bae11 

    - name: Login to Docker Hub
      uses: docker/login-action@b4ffde65f46336ab88eb53be808477a3936bae11 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@b4ffde65f46336ab88eb53be808477a3936bae11 
      with:
        push: true
        tags: lokeshmanifest/crud-api-latest:latest
        
  ex3-With-the-image:
    runs-on: ubuntu-latest

    steps:
    
    # - name: Scan image
    #   if: always()
    #   uses: anchore/scan-action@v3
    #   with:
    #     image: docker.io/lokeshmanifest/crud-api-latest:latest

    - name: Scan current project
      uses: anchore/scan-action@v3
      with:
        path: "."

    - name: upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
