name: Go Lang CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22.1'

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build
      run: go build -o myapp main.go

    - name: Run the app
      run: ./myapp

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: lokeshmanifest/crud-api-latest:latest
    
    - name: Scan image
      uses: anchore/scan-action@v3
      with:
        image: docker.io/lokeshmanifest/crud-api-latest:latest  # Specify the correct image name for scanning
    
    - name: Scan current project
      uses: anchore/scan-action@v3
      with:
        path: "."
